remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"
title: Broken Lantern
description: Hobby programming and electronics projects and blog
subtitle: Hobby programming and electronics projects and blog
locale: "en-US"
title_separator: "-"
logo: "/assets/images/lantern_icon_no_bg.png"
name: "David Cottingham"
url: https://brokenlantern.com
repository: davidcottingham/davidcottingham.github.io
search: true
search_full_content: true
atom_feed:
  path: /Blog/feed.xml
feed:
  path: /Blog/feed.xml
include: ["_pages"]

author:
  name: David Cottingham
  avatar: "/assets/images/lantern_icon_square_no_bg.png"
  #avatar: "https://avatars1.githubusercontent.com/u/857191"
  bio: #
  #bio: Just trying to figure things out. Hobby programming and electronics projects and blog
  #location: USA
  email: davidcottingham@gmail.com
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/davidcottingham"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/davidcottingham"

# Blog posts
permalink: /Blog/:year/:month/:day/:title/
timezone: America/New_York

tag_archive:
  type: liquid
  path: /Blog/Tags/

defaults:
  # blog posts
  - scope:
      path: "Blog"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      classes: wide
  # pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      share: true
  # sidebar nav
  - scope:
      path: ""
    values:
      sidebar:
        nav: "side"

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .bundle
  - .jekyll-assets-cache
